### ISSUE TITLE
Unaligned div with class "feature" - Consider using grid to correct alignment

### ISSUE THREAD

**Issue by Jony-Jas** [vinyashegde/interlace#11]
### The div element with the class "feature" appears to be unaligned and requires attention to ensure proper layout and positioning on the webpage. It is recommended to consider utilizing CSS grid to address this alignment issue effectively.

![Screenshot 2023-06-09 232216](https://github.com/vinyashegde/interlace.css/assets/74784363/42e6d03c-4fb0-4daf-a91d-0ffb7af2c31c)

**Comment by Savio629** [comment]
Nice catch!
Do you want to work on this issue @Jony-Jas ?

**Comment by Jony-Jas** [comment]
> Nice catch!
> Do you want to work on this issue @Jony-Jas ?

Yeah, sure 👍
